### ISSUE TITLE
First stab at package development

### ISSUE THREAD

**Issue by zoyafuso-NOAA** [afsc-gap-products/gapindex#11]
I forked this repo and started with an initial R package development to (1) pull data, (2) fill zeros and calculate CPUE, (3) calculate stratum biomass, and (4) calculate biomass across subareas and across region for the AI, GOA, EBS, EBS + NW, and NBS regions. The fork is located [here](https://github.com/zoyafuso-NOAA/design-based-indices). Could one or all of you run the code in the Initial Testing section and see whether the package installs properly and you can run the different functions. Reply on this thread if you run into problems. @MargaretSiple-NOAA probably has a better workflow to do the code testing, which I am open to learning about as we go along.

**Comment by MargaretSiple-NOAA** [comment]
Hi Zack! This looks really great. A clean and elegant base R rendition! 👑 I ran the test code. 

I ran into an error here: Running `AFSC.GAP.DBE::get_biomass_stratum()` (approx lines 15-24 of the `get_biomass_stratum.R` script):
![image](https://user-images.githubusercontent.com/73858992/202330134-fedd5876-969b-4fdc-a3a9-7d36e282bb8c.png)

I think this is a somewhat common issue with the `aggregate()` function but I have to be honest, I am terrible with that function. I poked around a little bit but don't know what the error means yet. 

Running R 4.2.1.

**Comment by zoyafuso-NOAA** [comment]
Thanks Megsie. I was working in R 4.0.2 and the aggregate function in >=4.2.0 for whatever reason will spit out that error when you put "formula =" in the aggregate function. That error was also observed in a different package issue [here](https://github.com/dreamRs/shinyWidgets/issues/491#issuecomment-1139145510). I removed the "formula =" bit in the get_biomass_stratum() and get_agg_biomass() functions so try reinstalling and rerunning and see whether it works now.
