### ISSUE TITLE
Question about GOA Big Skate

### ISSUE THREAD

**Issue by zoyafuso-NOAA** [afsc-gap-products/gapindex#13]
Hey @Ned-Laman-NOAA 

I'm doing some output checking with the package we've been working on consolidating index computation. Can you (hopefully quickly and painlessly) confirm something for me: in RACEBASE.CATCH, querying HAULJOIN = -5945 AND SPECIES_CODE = 420 produces one record with weight 0.088 kg (1 fish). In GOA.CPUE, that same query produces one record with zero weight and number of fish. Given the weight, was this record supposed to be big skate egg case (given the weight) and then changed to a different species code? This pattern popped up for handful of records in my output checks but luckily I believe this is the only species that I found to have this mismatch.

Thanks in advance and no rush,
Zack

**Comment by Ned-Laman-NOAA** [comment]
Good catch, Zack!
The record with weight 0.088 should be code 421 big skate egg case.
I'll put in a request to Nancy for the correction to RACEBase.

![Capture](https://user-images.githubusercontent.com/50336523/207648586-12a10174-1484-48d0-a4fa-8b3619f37a89.JPG)

**Comment by MargaretSiple-NOAA** [comment]
Wow, way to go Zack!

**Comment by zoyafuso-NOAA** [comment]
Awesome, I'll email Nancy as well because there are maybe 10 records that have a similar thing. Thanks for the response.
