### ISSUE TITLE
Compare design-based estimates between historical ones and dropping 700m+

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [afsc-gap-products/gapindex#4]
Look at historical design-based estimates and compare them to the same estimates for a case where we drop stations >700m. This is for Zack and Lewis's new GOA survey design. 

- [ ] Total biomass
- [ ] Age comps
- [ ] Length comps

**Comment by zoyafuso-NOAA** [comment]
I'll close this issue noting that the scripts to compare the BIOMASS, SIZECOMP, and AGECOMP tables between the existing schemata in Oracle and the new gapindex prodcuts in GAP_PRODUCTS were uploaded in these commits: 2ce862f and 21dbd52.
