### ISSUE TITLE
are all species in the spp_start_year table?

### ISSUE THREAD

**Issue by mkapur-noaa** [afsc-gap-products/gapindex#46]
### Issue

I ran the [vignette](https://github.com/afsc-gap-products/gapindex/blob/main/vignettes/ex_agecomps_ebs_standard.Rmd) code to generate `spp_start_year` and noticed that the code for BSAI Flathead Sole, 10130, is missing. Could this be clarified? Are data for that species not available via this package, simply not populated in that table [yet], or don't have any year constraints?
```
spp_start_year <-
  RODBC::sqlQuery(channel = sql_channel, 
                  query = "SELECT * FROM GAP_PRODUCTS.SPECIES_YEAR")

 spp_start_year
   SPECIES_CODE YEAR_STARTED
1           435         1999
2           436         1999
3           455         1999
4           456         1999
5           471         1999
6           472         1999
7           473         1999
8           474         1999
9           480         1988
10          481         1988
11        10110         1992
12        10112         1992
13        10212         1984
14        10261         1996
15        10262         1996
16        30051         2006
17        30052         2006
18        30152         1996
```

**Comment by zoyafuso-NOAA** [comment]
Hi @mkapur-noaa,

This table only highlights fish taxa with year constraints due to taxonomic ID confidence issues. For FHS, there is no year constraint, so it is not affected by that last for loop in the code.

**Comment by mkapur-noaa** [comment]
perfect, thanks for the clarification.
