### ISSUE TITLE
NAs in stratum means

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/gapindex#5]
NAs don't seem to be handled correctly in 03_get_biomass_stratum (lines 44 and 46). Should they be ignored? 

i.e., change:
mean_wgt_cpue = mean(WGTCPUE)

to:
mean_wgt_cpue = mean(WGTCPUE, na.rm = TRUE)

https://github.com/afsc-gap-products/design-based-indices/blob/1e30c05d2a53dc412b8737526121c60596e67211/R/03_get_biomass_stratum.R#L44

https://github.com/afsc-gap-products/design-based-indices/blob/1e30c05d2a53dc412b8737526121c60596e67211/R/03_get_biomass_stratum.R#L46

**Comment by sean-rohan-NOAA** [comment]
Or maybe it's this bit? 

https://github.com/afsc-gap-products/design-based-indices/blob/1e30c05d2a53dc412b8737526121c60596e67211/R/04_get_biomass_total.R#L36

**Comment by MargaretSiple-NOAA** [comment]
Thank you Sean! I fixed those two lines you mentioned and the total biomass calculation.
