### ISSUE TITLE
connecting to database via VM

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/gapindex#57]
I can't seem to connect to oracle via get_connected() when on a virtual machine, while I confirmed that it worked on my laptop using the same credentials.  

> sql_channel <- gapindex::get_connected()
Error in gapindex::get_connected() : 
  Unable to connect. Username or password may be incorrect. Check that you are connected to the network (e.g., VPN). Please re-enter.

I don't recall having this problem in the past, can somebody confirm that this works on their VM so I can identify what is causing this?

**Comment by MargaretSiple-NOAA** [comment]
Hi Lewis-- I am able to connect using `gapindex::get_connected()` from my VM, with the most recent version of `gapindex` (v 2.2.0).

I had this issue too in the past with my VM pre-`gapindex` and I remember having to get IT to set up the Oracle connection through R specifically for me. I forget what is different about it, but they had to specifically set it up for connecting through R. Sorry that's vague! It's all I remember from that experience.

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks Megsie.  I did have to configure the Oracle connection on my VM originally, and confirmed that it worked for some time, but perhaps something changed.  More quality time with IT in my future.

Lewis
