### ISSUE TITLE
Additional environmental measures associated with haul data

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/gapindex#59]
It would be great to have the ability to pull other environmental measures associated with the hauls beyond just temperature.  

Not sure if this is specific to this repository or should be thought about at a higher level in the gap products regime, but it would be great to have oxygen, salinity, etc. available in the haul data queries from R.  

Perhaps this will be easier to do by just integrating with output from gapctd?  Otherwise, it really should just be included in the haul data on racebase.

@EmilyMarkowitz-NOAA @sean-rohan-NOAA what do you think?

**Comment by sean-rohan-NOAA** [comment]
CTD data products are processed outside of the GAP database environments
and are, therefore, provided as a separate data product that includes the
original data files.

At this time, we do not have the operational capacity to integrate the data
streams into our database environments, especially when our at-sea data
collection systems are being replaced.
