### ISSUE TITLE
Area-specific complex calculations

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [afsc-gap-products/gapindex#62]
### Question
I have started incorporating the species complexes in the GOA DPR, and have run into a new (to me) challenge with rockfishes! The 
"Other Rockfish" category has a group of species (canary RF, quillback RF, rosethorn, yelloweye, and a few others) that are included in the Other Rockfish assessment "in all areas west of East Yakutat/Southeast, but in the Demersal Shelf Rockfish assessment otherwise."  The assessment is [here](https://apps-afsc.fisheries.noaa.gov/refm/docs/2021/GOAorock.pdf) and the members of the complexes are listed in Table 16.1.

The first approach that comes to mind for me is to calculate stratum biomasses for ORocks including and not including that group of species, then sum `stratum_biomass_all_west` + `stratum_biomass_subset_east` to get total B. Does that sound right to you? I don't think anything in gapindex needs to change for this one scenario (I'm pretty sure this is the only complex where this happens) but wanted to get advice/confirmation.

I haven't run into this region-specific complex composition yet, so this is a first for me.

**Comment by zoyafuso-NOAA** [comment]
Hey Megsie,

If I'm comprehending the assessment document correctly, that should work. Look at this [script](https://github.com/afsc-gap-products/gap_products/blob/main/code/goa_split_fractions/goa_split_fractions.R) for how to do the split-fractions calculations with gapindex. Let me know if you have other questions.

**Comment by MargaretSiple-NOAA** [comment]
Yes! Split fractions I think will work for this. I also heard back from Cindy T about the OROX assessment from 2025 onwards, and it sounds like their species list is not going to contain those demersal shelf RF anyway in the future so I think my question is answered on all fronts. I may need that code for another complex (tbd) so I'll keep it on hand. Thanks again.
